const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8');

const indexHtml = read('index.html');
const configJs = read('js/config.js');
const appJs = read('js/app.js');
const chatLogicJs = read('js/chat-logic.js');
const packageJson = JSON.parse(read('package.json'));

assert.match(configJs, /defaultModel:\s*'medgemma1\.5:4b'/);
assert.match(configJs, /'gpt-oss:120b-cloud'/);
assert.match(configJs, /defaultModelPreference:\s*'auto'/);
assert.match(configJs, /gptModel:\s*'gpt-oss:120b-cloud'/);
assert.match(configJs, /medModel:\s*'medgemma1\.5:4b'/);

assert.doesNotMatch(indexHtml, /<label[^>]+for="systemPromptTextarea"[^>]*>\s*System Prompt\s*<\/label>/);
assert.match(indexHtml, /id="auraStyleSelect"/);
assert.match(indexHtml, /id="responseDetailSelect"/);
assert.match(indexHtml, /id="advancedPromptToggle"/);
assert.match(indexHtml, /id="advancedPromptTextarea"/);
assert.doesNotMatch(indexHtml, /class="browser-toolbar"/);
assert.match(indexHtml, /<textarea id="userInput" rows="1"/);
assert.match(indexHtml, /id="chatMessages"[^>]+role="log"[^>]+aria-live="polite"/);
assert.match(indexHtml, /<details class="advanced-model-panel">/);
assert.match(indexHtml, /id="feedbackLearningStatusText"/);
assert.match(indexHtml, /id="clearFeedbackButton"/);
assert.match(indexHtml, /<script src="js\/model-routing\.js"><\/script>\s*<script src="js\/turn-policy\.js"><\/script>\s*<script src="js\/tool-artifacts\.js"><\/script>\s*<script src="js\/feedback-learning\.js"><\/script>\s*<script src="js\/chat-logic\.js"><\/script>/);
assert.match(indexHtml, /<option value="auto">Auto/);
assert.match(packageJson.scripts.check, /node --check lib\/memory-results\.js/);
assert.match(packageJson.scripts.check, /node --check js\/turn-policy\.js/);
assert.match(packageJson.scripts.check, /node --check js\/tool-artifacts\.js/);
assert.match(packageJson.scripts.check, /node --check js\/feedback-learning\.js/);
assert.match(packageJson.scripts.check, /node tests\/memory-results\.test\.js/);
assert.match(packageJson.scripts.check, /node tests\/turn-policy\.test\.js/);
assert.match(packageJson.scripts.check, /node tests\/tool-artifacts\.test\.js/);
assert.match(packageJson.scripts.check, /node tests\/feedback-learning\.test\.js/);
assert.match(packageJson.scripts.check, /node tests\/response-examples\.test\.js/);

assert.match(appJs, /function escapeOptionValue/);
assert.match(appJs, /getPinnedModelNames/);
assert.match(appJs, /advancedPromptToggle/);
assert.match(appJs, /auraStyleSelect/);
assert.match(appJs, /responseDetailSelect/);
assert.match(appJs, /AUTO_MODEL_OPTION/);
assert.match(appJs, /window\.AURA_AVAILABLE_MODELS/);
assert.match(appJs, /let responseInFlight = false/);
assert.match(appJs, /chatManager\.addMessageToChat\(requestChatId/);
assert.match(appJs, /getOllamaResponse\(\s*message,\s*null,\s*documentText,\s*requestChatId\s*\)/);
assert.match(appJs, /async function retryWithFeedback/);
assert.match(appJs, /promotePersonalExample/);

assert.match(chatLogicJs, /PROMPT_OVERRIDE_ENABLED/);
assert.match(chatLogicJs, /function getEffectiveSystemPrompt/);
assert.match(chatLogicJs, /buildResponseSystemPrompt\(getEffectiveSystemPrompt\(\), activeModel\)/);
assert.match(chatLogicJs, /function getModelPreference/);
assert.match(chatLogicJs, /async function _callLLM\(prompt, \{/);
assert.match(chatLogicJs, /\.\.\.\(inferencePolicy\.think \? \{ think: inferencePolicy\.think \} : \{\}\)/);
assert.match(chatLogicJs, /num_predict:\s*inferencePolicy\.maxTokens/);
assert.match(chatLogicJs, /function runModelRoutingAgent/);
assert.match(chatLogicJs, /modelDecision:\s*modelRouting\.modelDecision/);
assert.match(chatLogicJs, /MEDICAL_RESPONSE_REVIEW/);
assert.match(chatLogicJs, /async function reviewMedicalReplyIfNeeded/);
assert.match(chatLogicJs, /AURA_TURN_POLICY\.hasToolRefusal\(userMessage\)/);
assert.match(chatLogicJs, /AURA_TURN_POLICY\.hasImmediateGroundingNeed\(userMessage\)/);
assert.match(chatLogicJs, /async function getOllamaResponse\([\s\S]*chatId = chatManager\.getActiveChatId\(\)/);
assert.match(chatLogicJs, /feedbackLearning:\s*window\.AURA_FEEDBACK\.createState\(\)/);
assert.match(chatLogicJs, /getPersonalExampleCandidate/);
